Assets/NewComputeShader.compute
Assets/SyftController.cs
notebooks/Server Notebook.ipynb

Elementwise subtraction is now working on the gpu.
Finished the compute shader tutorial that @iamtrask shared. Implemented elementwise subtraction, which was mostly a duplicate of the multiplication function that was already there. Got things working on the python side. Made sure to use the gpu version.

add ComputeShader for elementwise subtraction and call from python.

---

Assets/BasicNeuralNetwork.cs
Assets/BasicNeuralNetwork.cs.meta
Assets/main.unity
ProjectSettings/QualitySettings.asset
notebooks/basic-python-network.ipynb

a basic neural network in c#

---

README.md

Adjusted the README to be clearer. Added a few notes for troubleshooting.

Adjusted readme

---

Assets/OpenMined/Network/Controllers/SyftController.cs
Assets/OpenMined/Syft/Tensor/FloatTensor.cs
notebooks/Syft Tensor Example Notebook.ipynb

Expose scalar_multiplication and add tensor print

---

README.md

Added the docs repo link to the README.

added the docs repo link to the README

---

Assets/OpenMined.Tests/Editor/FloatTensorTest.cs
Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs
Assets/OpenMined/Syft/Tensor/FloatTensor.cs

Feat/float tensor  add function tests

---

Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs
Assets/OpenMined/Syft/Tensor/FloatTensor.cs

Hello,
I believe I have "fixed" the constructor implementations. I am not sure if this is the right way to allocate memory on GPU, however I was following the convention in the `Gpu` method.
I also parallelized `Add` method and changed how it creates the output `FloatTensor`. Previous implementation was passing `this.data` as a parameter, which would create an unnecessary copy of the data. We can use this function's CPU implementation as a reference for other ops as well.

Fixed constructor implementations 

---

Assets/OpenMined.Tests/Editor/FloatTensorTest.cs
Assets/OpenMined/Network/Controllers/SyftController.cs
Assets/OpenMined/Syft/Math/Shaders/FloatTensorShaders.compute
Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs
Assets/OpenMined/Syft/Tensor/FloatTensor.ShaderOps.cs

Implemented in place addition for issue [#414](https://github.com/OpenMined/PySyft/issues/414) and created a test for it

Added Add_() to backend

---

Assets/OpenMined.Tests/Editor/FloatTensorTest.cs
Assets/OpenMined/Network/Controllers/SyftController.cs
Assets/OpenMined/Syft/Math/Shaders/FloatTensorShaders.compute
Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs
Assets/OpenMined/Syft/Tensor/FloatTensor.ShaderOps.cs

related https://github.com/OpenMined/PySyft/issues/630

added `Zero` to OpenMined backend

---

UnityProject/Assets/OpenMined.Tests/Editor/FloatTensorTest.cs
UnityProject/Assets/OpenMined/Network/Controllers/SyftController.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.cs

includes test
move delete tensor into FloatTensor.cs

Add copy constructor

---

UnityProject/Assets/OpenMined.Tests/Editor/FloatTensorTest.cs
UnityProject/Assets/OpenMined/Syft/Math/Shaders/FloatTensorShaders.compute
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.MutatingOps.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.ShaderOps.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.cs

Implemented Floor_() for issue [#481](https://github.com/OpenMined/PySyft/issues/481)

Implement inline floor Functionality in FloatTensor

---

UnityProject/Assets/OpenMined.Tests/Editor/FloatTensorTest.cs
UnityProject/Assets/OpenMined/Syft/Math/Shaders/FloatTensorShaders.compute
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.ShaderOps.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.cs

closes https://github.com/OpenMined/PySyft/issues/608
closes https://github.com/OpenMined/PySyft/issues/607

added tanh to FloatTensor

---

UnityProject/Assets/OpenMined.Tests/Editor/FloatTensorTest.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.cs

Addresses https://github.com/OpenMined/PySyft/issues/505

Implements IsContiguous on Float Tensor class

---

UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs

Fixed - There is public function defined inside another public function

fixed FloatTensor.Ops.cs code 

---

UnityProject/Assets/OpenMined.Tests/Editor/FloatTensorTest.cs
UnityProject/Assets/OpenMined/Syft/Math/Shaders/FloatTensorShaders.compute
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.ShaderOps.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.cs

1. adds acos/acos_
2. adds asin/asin_
3. adds atan/atan_

adds more math functions

---

UnityProject/Assets/OpenMined/Syft/Math/Shaders/FloatTensorShaders.compute
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.MutatingOps.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.ShaderOps.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.cs
notebooks/Syft Tensor Example Notebook.ipynb

This PL contains changes for Pow element and scalar, following suit like `Mul`. 
There were two functions of a previous implementation that was only used as a helper function for `Mul`. I'm did not find it being used anywhere else but I'm not 100% sure. I changed the implementation from just a scalar to scalar and element wise (following pytorchs implementation).
Unit test is still missing.

Pow function

---

UnityProject/Assets/OpenMined.Tests/Editor/FloatTensorTest.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.cs
notebooks/MLP Demo.ipynb

Needed 2D transpose to get my notebook working
implemented using [list], which is not the fastest, but hopefully easy to understand
think very useful for first round implementations
"public float this[long index]" is a neat access abstraction based "public float this[params long[] indices]" which is really cool
made GetIndex public, so that I could write a test to prove that the new function GetIndices is its inverse
Related PR https://github.com/OpenMined/PySyft/pull/672/
Addresses https://github.com/OpenMined/OpenMined/issues/25 for CPU

Make MLP demo work

---

UnityProject/Assets/OpenMined.Tests/Editor/FloatTensorTest.cs
UnityProject/Assets/OpenMined/Syft/Math/Shaders/FloatTensorShaders.compute
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.ShaderOps.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.cs

Addresses following issues from PySyft repo:

Feature/float tensor  mv add

---

.gitignore
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.cs
integration/tests.py

these live in the `integration/` dir under root.  There are only ones
written for `abs` right now but we can add more over time.
https://github.com/OpenMined/PySyft/issues/633

added integration tests

---

UnityProject/Assets/OpenMined.Tests/Editor/FloatTensorTest.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.cs
notebooks/OpenMined_Arsenal_ShowCase.ipynb

added tests and example to Arsenal Show Case Notebook
closes https://github.com/OpenMined/PySyft/issues/591
closes https://github.com/OpenMined/PySyft/issues/592

squeeze functionality plus inline

---

UnityProject/Assets/OpenMined/UI/Open.shader
UnityProject/Assets/OpenMined/UI/Open.shader.meta
UnityProject/Assets/OpenMined/UI/OpenMinedMaterial.mat
UnityProject/Assets/OpenMined/UI/OpenMinedMaterial.mat.meta
UnityProject/Assets/OpenMinedMain.unity

find the console easier to read this way .. looks more like a server?!
This is kind of silly so feel free to close if you're not into it lol
preview:

make the scene black

---

UnityProject/Assets/OpenMined.Tests/Editor/FloatTensorTest.cs
UnityProject/Assets/OpenMined/Syft/Math/Shaders/FloatTensorShaders.compute
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.ShaderOps.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.cs

Hello,
This pull request should add the Exp() for FloatTensor. 
Thank you!

Add Exp() to FloatTensor (#473)

---

notebooks/MNIST Basic.ipynb

I will do another notebook that is good at the entire dataset once i can
easly set up tensors for the proper labels

MNIST recognize a 6

---

UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.cs
notebooks/Syft Tensor Example Notebook.ipynb

Implementing view_as

---

UnityProject/Assets/OpenMined.Tests/Editor/FloatTensorGpuTest.cs
UnityProject/Assets/OpenMined.Tests/Editor/FloatTensorTest.cs
UnityProject/Assets/OpenMined/Syft/Math/Shaders/FloatTensorShaders.compute
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.ShaderOps.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.cs

Inline version of neg function added, as per issue #540

New feature/neg 

---

UnityProject/Assets/OpenMined.Tests/Editor/FloatTensor/FloatTensorGpuTest.cs
UnityProject/Assets/OpenMined.Tests/Editor/FloatTensor/FloatTensorTest.cs
UnityProject/Assets/OpenMined.Tests/Editor/Model/ModelTest.cs
UnityProject/Assets/OpenMined/Syft/Model/Linear.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Helpers.cs

> They were back...
They wanted revenge...
They lost...
Compiler warnings are out again ;)

fix|compiler warnings

---

UnityProject/Assets/OpenMined/Syft/Tensor/Ops/Shaders/FloatTensorShaders.compute

Was missed in
https://github.com/OpenMined/OpenMined/pull/225

 Add rsqrt_ shader computation

---

UnityProject/Assets/OpenMined.Tests/Editor/Autograd.meta
UnityProject/Assets/OpenMined.Tests/Editor/Autograd/AutogradTest.cs
UnityProject/Assets/OpenMined.Tests/Editor/Autograd/AutogradTest.cs.meta
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Autograd.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Graph.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs
UnityProject/Assets/OpenMinedMain.unity
UnityProject/ProjectSettings/ProjectVersion.txt

also added a new section for autograd tests and a sneaky sigmoid autograd test!
also fixed a crash in autograd

autograd implements for tanh

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Added PR and Issue Templates. 
Sister PR in PySyft [here](https://github.com/OpenMined/PySyft/pull/719)

Added PR and Issue Templates

---

UnityProject/Assets/OpenMined.Tests/Editor/FloatTensor/FloatTensorAutogradTest.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Autograd.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs

Support for abs autograd.
Added tests in FloatTensorAutograd.cs.

support for abs autograd

---

UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Autograd.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Graph.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs
notebooks/torch/OpenMined PyTorch - CartPole.ipynb

Added backprop for index_select

added backprop for index_select

---

UnityProject/Assets/OpenMined/Syft/Tensor/BaseTensor.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs

The base tensor had the wrong isContiguous implementation. This fixes that.

fix base tensor isContiguous method

---

UnityProject/Assets/OpenMined/Network/Controllers/SyftController.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.cs
UnityProject/Assets/OpenMined/Syft/Tensor/Functional.cs
notebooks/Test Functional Implementations.ipynb
tutorials/HowToAddFunctionToFloatTensor.md

Added some new functions to Functional.cs:
- Random: generates a FloatTensor of a given size with random numbers.
- Zeros: generates a FloatTensor of a given size with zeros.
- Ones: generates a FloatTensor of a given size with ones.
Tested in the added notebook "Test Functional Implementations" in which new functions can also be tested.

Add functions to functional.cs

---

UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.cs
tutorials/HowToAddFunctionToFloatTensor.md

Added a random functionality for Float Tensor
Fixes #560 Implement inline random Functionality in FloatTensor with CPU/GPU Backend Support
Can be tested by creating a FloatTensor a with some data and then calling a.random_()
* CPU: yes
* GPU: not yet implemented
* Unity Version: 2017.2of3
PS this is my first Pull Request so feedback is welcome!

Implement random float tensor function

---

UnityProject/Assets/OpenMined/Network/Controllers/SyftController.cs
UnityProject/Assets/OpenMined/Syft/NN.meta
UnityProject/Assets/OpenMined/Syft/NN/Layer.cs
UnityProject/Assets/OpenMined/Syft/Optim/SGD.cs
notebooks/demos/MLP Using Optimizer.ipynb

Adds support for optional (default to 0.0) momentum and learning rate decay for the Stochastic Gradient Descent SGD optimizer. 
Run the notebook: notebooks/Openmined/notebooks/demos/MLP Using Optimizer.ipynb
Remove momentum and decay to validate that the loss is the same as before

Momentum and Learning Rate Decay for SGD Optimizer

---

UnityProject/Assets/OpenMined/Network/Controllers/SyftController.cs
UnityProject/Assets/OpenMined/Network/Utils/Command.cs
UnityProject/Assets/OpenMined/Syft/NN.meta
UnityProject/Assets/OpenMined/Syft/NN/Layer.cs
UnityProject/Assets/OpenMined/Syft/Optim/Adam.cs
UnityProject/Assets/OpenMined/Syft/Optim/Adam.cs.meta
UnityProject/Assets/OpenMined/Syft/Optim/Optimizer.cs
UnityProject/Assets/OpenMined/Syft/Optim/Optimizer.cs.meta
UnityProject/Assets/OpenMined/Syft/Optim/RMSProp.cs
UnityProject/Assets/OpenMined/Syft/Optim/RMSProp.cs.meta
UnityProject/Assets/OpenMined/Syft/Optim/SGD.cs
notebooks/demos/MLP Using Optimizer.ipynb

- Base Optimizer class to inherit from.
- Fixed momentum issue with SGD optimizer
- Added RMSProp
- Added Adam
Through the MLP with Optimizer notebook

Optimizer improvements (SGD, Adam, RMSProp)

---

UnityProject/Assets/OpenMined/Network/Controllers/SyftController.cs
UnityProject/Assets/OpenMined/Syft/Tensor/Functional.cs
notebooks/tests/Test Random Seed.ipynb

Implemented a set random seed function to make it easier to do consistent test runs.
Goes together with 
I included a notebook with extensive tests.

Set random seed function

---

UnityProject/Assets/OpenMined/Syft/Tensor/Factories/FloatTensorFactory.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.cs

See: https://github.com/OpenMined/PySyft/pull/749

delete tensor after usage

---

UnityProject/Assets/OpenMined.Tests/Editor/FloatTensor/FloatTensorAutogradTest.cs
UnityProject/Assets/OpenMined.Tests/Editor/FloatTensor/FloatTensorGpuTest.cs
UnityProject/Assets/OpenMined.Tests/Editor/FloatTensor/FloatTensorTest.cs
UnityProject/Assets/OpenMined.Tests/Editor/IntTensor.meta
UnityProject/Assets/OpenMined.Tests/Editor/IntTensor/IntTensorGpuTest.cs
UnityProject/Assets/OpenMined.Tests/Editor/IntTensor/IntTensorGpuTest.cs.meta
UnityProject/Assets/OpenMined.Tests/Editor/IntTensor/IntTensorTest.cs
UnityProject/Assets/OpenMined.Tests/Editor/IntTensor/IntTensorTest.cs.meta
UnityProject/Assets/OpenMined/Syft/Tensor/IntTensor.cs
UnityProject/ProjectSettings/ProjectVersion.txt

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
* CPU:
* GPU:

initial setup for IntTensor add

---

UnityProject/Assets/OpenMined/Network/Controllers/SyftController.cs
UnityProject/Assets/OpenMined/Syft/NN/Loss/CategoricalCrossEntropyLoss.cs
UnityProject/Assets/OpenMined/Syft/NN/Loss/CategoricalCrossEntropyLoss.cs.meta

Added categorical cross entropy

added categorical cross entropy

---

UnityProject/Assets/OpenMined.Tests/Editor/IntTensor/IntTensorTest.cs
UnityProject/Assets/OpenMined/Syft/Tensor/IntTensor.cs

Implement abs function for IntTensor with CPU
Fixes https://github.com/OpenMined/PySyft/issues/762
PySyft PR: https://github.com/OpenMined/PySyft/pull/1278

implement abs function for IntTensor with spec

---

UnityProject/Library/LastSceneManagerSetup.txt

This sets a default scene so we no longer have to manually open OpenMinedMain.scene.
@bendecoste @gavinuhma  tested it

default scene woooooooooooo

---

UnityProject/Assets/OpenMined.Tests/Editor/IntTensor/IntTensorTest.cs
UnityProject/Assets/OpenMined/Syft/Tensor/IntTensor.cs

PySyft PR: https://github.com/OpenMined/PySyft/pull/1280
Fixes #1246

Add trace function to IntTensor with spec

---

UnityProject/Assets/OpenMined.Tests/Editor/IntTensor/IntTensorGpuTest.cs
UnityProject/Assets/OpenMined/Syft/Tensor/IntTensor.cs
UnityProject/Assets/OpenMined/Syft/Tensor/Ops/Shaders/Shaders.compute

Fixes https://github.com/OpenMined/PySyft/issues/764
Implemented passing test in IntTensorGpuTest.cs

Implement the Abs function for IntTensor on the GPU

---

notebooks/keras/Keras Interface Demo - MNIST MLP.ipynb

Added a demo of model.evaluate() implemented in https://github.com/OpenMined/OpenMined/pull/316  to the Keras notebook.
Ran the notebook and tested the metrics results.

Demo of model.evaluate() in the keras notebook

---

UnityProject/Assets/OpenMined.Tests/Editor/IntTensor/IntTensorGpuTest.cs
UnityProject/Assets/OpenMined.Tests/Editor/IntTensor/IntTensorTest.cs
UnityProject/Assets/OpenMined/Syft/Tensor/IntTensor.cs
UnityProject/Assets/OpenMined/Syft/Tensor/Ops/Shaders/Shaders.compute

Addresses PySyft #814, #815, #816, #817. 
* CPU:
* GPU:

Added Sub and inline Sub for CPU and GPU

---

UnityProject/Assets/OpenMined/Network/Controllers/Grid.cs
UnityProject/Assets/OpenMined/Network/Servers/BlockChain.cs
UnityProject/Assets/OpenMined/Network/Servers/Request.cs
UnityProject/Assets/OpenMined/Network/Servers/SyftServer.cs
UnityProject/Assets/OpenMined/UI/Login.cs
UnityProject/ProjectSettings/ProjectVersion.txt

Prototype upload weights from trainer.

Upload weights

---

UnityProject/Assets/OpenMined/Network/Controllers/Grid.cs
UnityProject/Assets/OpenMined/UI/Log.cs

fix compile error

---

UnityProject/Assets/OpenMined/Syft/NN/Linear.cs

fixes https://github.com/OpenMined/OpenMined/issues/386

fix backward weight shape in linear layer

---

UnityProject/Assets/OpenMined/Network/Controllers/Grid.cs

Small addition to Grid.cs making it show how many models are trained already instead of just "In progress".
Tested in the Grid example notebook.

Show progress grid

---

notebooks/grid/Grid Example.ipynb

Updated the Grid example notebook to make it more clear how to setup Grid and what's going on at each step.
Ran through the notebook and everything seems to work.

Update the Grid example notebook

---

notebooks/ml-agents/CartPole-v0_ML_Agent.ipynb

Added the Notebook to train the ML Agent to solve "CartPole-v0" on Unity with OpenMined.
* Os: W10

Notebook for RL CartPole-v0 with ML Agent and OM backend

---

notebooks/grid/Grid Example.ipynb

Changed 1.0 to 1 in grid example for clarity
* CPU:
* GPU:

Updated inputs in grid example to all have the same format

---

UnityProject/Assets/OpenMined/Syft/Tensor/BaseTensor.Helpers.cs
UnityProject/Assets/OpenMined/Syft/Tensor/BaseTensor.Helpers.cs.meta
UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Helpers.cs
UnityProject/Assets/OpenMined/Syft/Tensor/IntTensor.Helpers.cs
UnityProject/Assets/OpenMined/Syft/Tensor/IntTensor.Helpers.cs.meta

Added CPU tensor sort helper functions. Added a .helper file for the BasicTensor which contains the core sort function, which utilizes highly optimized .NET sort implementation.
Sort Notes:
If the partition size is fewer than 16 elements, it uses an insertion sort algorithm. If the number of partitions exceeds 2 * LogN, where N is the range of the input array, it uses a Heapsort algorithm. Otherwise, it uses a Quicksort algorithm. 
An additionally note : it is an unstable sort, that is, if two elements are equal, their order is not guaranteed to  be preserved
IComparer class were added to the IntTensor and FloatTensor classes (in Tensor.helper.cs files), which implement the comparer for Ascending and Descending Sorting. These are Class specific and can easily be extended for more complex …

CPU Tensor Sort

---

UnityProject/Assets/OpenMined.Tests/Editor/IntTensor/IntTensorTest.cs
UnityProject/Assets/OpenMined/Syft/Tensor/IntTensor.Ops.cs
UnityProject/Assets/OpenMined/Syft/Tensor/IntTensor.cs
integration/test_int_tensor.py
notebooks/tests/Test Tensor Function Implementations.ipynb

This pull request resolves issue #1242 in PySyft . This pull request is the OpenMined portion of the implementation. See the pull request  OpenMined/PySyft/pull/1317  for the PySyft portion
Fixes #1242 in PySyft
* CPU: iMac (21.5-inch, Mid 2011)  2.8 GHz Intel Core i7
* GPU: AMD Radeon HD 6770M 512 MB
* PySyft Version: 0.1.0
* Unity Version: 2017.3.0f3
* OpenMined Unity App Version: Latest

implemented topk for intTensor

---

UnityProject/Assets/OpenMined.Tests/Editor/IntTensor/IntTensorTest.cs
UnityProject/Assets/OpenMined/Syft/Tensor/IntTensor.Ops.cs
UnityProject/Assets/OpenMined/Syft/Tensor/IntTensor.cs
notebooks/tests/Test Tensor Function Implementations.ipynb

This PR adds the unfold function for IntTensor OpenMined/PySyft#1267
Fixes OpenMined/PySyft#1267
* CPU: Intel Code i7 (4th Gen), Jupyter Notebook, Python 3.6
* GPU: n/a
* PySyft Version: 0.1.0
* Unity Version: 2017.2.0f3 Personal
* OpenMined Unity App Version: latest

Implement inline Unfold function for IntTensor

---

tutorials/WhyUnity.md

I edited the grammar of the documentation.
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
* CPU:
* GPU:

Edited Grammer
