OpenMined/UnityWorker

- Assets/OpenMined/Network/Controllers/SyftController.cs
- Assets/OpenMined/Syft/Tensor/FloatTensor.Disposable.cs
- Assets/OpenMined/Syft/Tensor/FloatTensor.MemoryOps.cs
I would be very happy if someone could go through how a tensor is removed and deleted from the server. (e.g. if dispose is used correctly) 
This is the backend support for the destructor and delete methods in PySyft. I couldn't properly test this, since shader functionality is still tightly integrated.
> Backend functionality for deleting PySyft.FloatTensor 

- notebooks/Syft Tensor Example Notebook.ipynb
This makes it quicker to develop locally as you don't need to
continually reload the notebook to see your local changes uptaken
> reload pysft controller and create a new controller in the same block

- UnityProject/Assets/OpenMined.Tests/Editor/FloatTensorTest.cs
they were failing because was checking against too many decimals had to
round first and then check
> fix sinh tests

- .travis.yml
Howdy!
To make Travis builds work again:
- push Unity install after OpenSSL upgrade
- use Homebrew's Python (instead of system Python)
Cheers
> ci|travis.yml update

- UnityProject/Assets/OpenMined.Tests/Editor/FloatTensorTest.cs
- UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs
- UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.cs
As per https://github.com/OpenMined/PySyft/issues/586
This adds `SizeTensor()` which:
- mirrors `size()` from Syft (the method Size already exists, hence this name)
- returns a FloatTensor that basically contains `int`s (note that Pytorch has a SizeTensor for this). For the moment, I guess using FloatTensor is sufficient, and it leverages the messaging mechanism.
The corresponding PR in Syft will be linked here.
Acceptance criteria:
> feature|add `size() <-> SizeTensor()` and test

- UnityProject/Assets/OpenMined/UI.meta
- UnityProject/Assets/OpenMined/UI/Log.cs
- UnityProject/Assets/OpenMined/UI/Log.cs.meta
- UnityProject/Assets/OpenMinedMain.unity
Added logging to the UI to make it easier to debug on devices (like Xbox).
Collaborated with @alberduris who had a cool idea to grab the `UnityEngine.Debug` logs. So we didn't have to change a bunch of log lines! As seen here: https://gist.github.com/alberduris/7bcc7705c3fd9dc50d9bb45c4fda5b39
Optionally you can call `OpenMined.UI.Log.LogFormat()` directly, which will skip logging to the Unity console but still supports rich text.
> log to the ui

- UnityProject/Assets/OpenMined.Tests/Editor/FloatTensorTest.cs
- UnityProject/Assets/OpenMined/Syft/Math/Shaders/FloatTensorShaders.compute
- UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs
Introduce checks to Sigmoid evaluation in order to avoid overflow for large data values.
Reference: https://timvieira.github.io/blog/post/2014/02/11/exp-normalize-trick/
> Numerical stability for Sigmoid

- .travis.yml
- UnityProject/Assets/OpenMined.Tests/Editor/FloatTensorGpuTest.cs
- UnityProject/Assets/OpenMined.Tests/Editor/FloatTensorTest.cs
- UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Disposable.cs
- UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Encryption.cs
- UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.ShaderOps.cs
- UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.cs
**Rationale**:
- Too many warnings (currently 17) make us finally ignore them. Of course, this can be solved later, but why wait for it? 😉 
- We now have a clean console again, which is a little incentive to keep it clean
What was done:
- Fixed the warnings
- Silenced one kind of warning `CS0420` regarding "ref to volatile" (it cannot be solved otherwise)
> Compiler warnings are gone (how sad)

- UnityProject/.idea/.idea.UnityProject/.idea/workspace.xml
- UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs
This pr adds a contiguous checks at the beginning of most functions. Most of our
functions don't support non-contiguous tensors.
Also changed the definition of IsContiguous a bit. Noticed that in
pytorh a contiguous tensor must have its last dimension's stride set to
1 AND not have other strides set to zero. If this doesn't work let me
know!
Another thing that is needed in the future is a function to turn a
non-contiguous tensor into a contiguous one. Not really sure how to
implement this right now.
Check out this discussion for more: https://github.com/OpenMined/OpenMined/issues/205
> non-contiguous checks at beginning of functions

- UnityProject/Assets/OpenMined/Network/Controllers/SyftController.cs
- UnityProject/Assets/OpenMined/Syft/NN/Linear.cs
- notebooks/tests/Test Xavier Initialization.ipynb
Implemented Xavier Weight Initialization and applied it to the Linear model. 
Xavier weight initialization means initializing the parameter weights on a uniform distribution within the range of: `-sqrt(1/num_inputs), sqrt(1/num_inputs)` which has been shown to improve model stability/convergence. 
I added a notebook that tests the implementation and shows the model trains faster using Xavier weight initialization.
> Implement Xavier Weight Initialization and apply to Linear model

- UnityProject/Assets/OpenMined.Tests/Editor/FloatTensor/FloatTensorTest.cs
- UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs
- UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.cs
Fixed op naming issue with functions that call Reduce which was leading to keepdim not functioning properly because the same op was getting reused. Also added Var, Std, Norm and Split (#627, #593, #544 and #588) in FloatTensor.Ops.cs and FloatTensor.cs. Replaced existing Std function which had limited functionality with Var and Std which calls Var. 
* CPU:
* GPU:
> Fixed issue with functions that call Reduce, added Var, Std, Norm and Split.

- UnityProject/Assets/OpenMined/Syft/NN/Layer.cs
- UnityProject/Assets/OpenMined/Syft/Tensor/Factories/FloatTensorFactory.cs
- UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs
- UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.cs
Create an evaluation function that runs in Unity and returns the predictions and the test loss. Also made all the losses an average instead of a sum, so they are easier to compare.
Updated the model.evaluate() function in Pysyft so that you can use any metric (also custom metric functions) that take y_pred and y_true.
Tested at the end of the Keras notebook. 
There are still two minor issues:
1) The test batch size has to be the same as the training batch size. But this is a separate issue that has to be fixed overall and also is an issue when you try to do model.predict() for a few specific examples (see Issue https://github.com/OpenMined/OpenMined/issues/315 ). For now, just keep training batch_size and test batch_size the same.
2) We need test mode for the Forward() function in order …
> Create function to evaluate the model in unity

- UnityProject/Assets/OpenMinedMain.unity
turned off lighting settings to avoid a continuous stream of compilation errors stating: `Failed executing external process for 'Bake Runtime' job.`
> fix `Failed executing external process for 'Bake Runtime' job.` error in Ubuntu

- UnityProject/Assets/OpenMined.Tests/Editor/IntTensor/IntTensorGpuTest.cs
- UnityProject/Assets/OpenMined/Syft/Tensor/IntTensor.cs
- UnityProject/Assets/OpenMined/Syft/Tensor/Ops/Shaders/Shaders.compute
Adding the GPU implementation of neg()  to our IntTensor class with the appropriate functionality, returning a new tensor.
https://github.com/OpenMined/PySyft/issues/1077
* CPU: mac 2015 mbp 15" (2.8 GHz Intel Core i7)
* GPU: AMD Radeon R9 M370X 2 GB - Intel Iris Pro 1536 MB
* PySyft Version: latest
* Unity Version: latest
* OpenMined Unity App Version: latest, master
- [] New and existing unit tests pass locally with my changes
> Add negate gpu for int tensor

- UnityProject/Assets/OpenMined.Tests/Editor/IntTensor/IntTensorGpuTest.cs
- UnityProject/Assets/OpenMined.Tests/Editor/IntTensor/IntTensorTest.cs
- UnityProject/Assets/OpenMined/Syft/Tensor/IntTensor.cs
- UnityProject/Assets/OpenMined/Syft/Tensor/Ops/Shaders/Shaders.compute
Implemented IntTensor negate for CPU and GPU in Unity with tests. 
Fixes 
OpenMined/PySyft#1075 
OpenMined/PySyft#1076 
OpenMined/PySyft#1077  
OpenMined/PySyft#1078
* CPU:
* GPU:
> implemented negate in CPU and GPU for IntTensor and tests #1075, #1076, #1077, #1078

- UnityProject/Assets/OpenMined/Syft/Tensor/BaseTensor.cs
- UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Graph.cs
- UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs
- UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.cs
Keep track of the usage count of tensor
Keep track of the usage count of each tensor using a variable `Usage_count`. Increase this variable by 1 when a tensor is re-used (using hookgraph) and only delete a tensor if it's just used once.
This fixes the issue described here: https://github.com/OpenMined/PySyft/pull/761
Tested in jupyter notebook with the following code:
```a = FloatTensor(data)
b = a.max()
c = a.max()
c.delete_after_use = True
b.delete_after_use = True
c = 0
print(b)
b = 0
```
After which the tensor is deleted in the Unity log. Also logging the value of usage_count it shows that it increases when you re-use the tensor and then decreases when you remove one variable.
> Keep track of the usage count of tensor

- UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Graph.cs
- UnityProject/Assets/OpenMined/Syft/Tensor/FloatTensor.Ops.cs
As mentioned here: https://github.com/OpenMined/OpenMined/pull/370 when you do an operation without storing the value and then try to do the same operation again, the tensor will try to retrieve the result of the operation from the graph eventhough it doesn't exist anymore.
To solve this I make sure to delete the FloatTensor from the children_indices in its creator(s). I think this should completely solve the issue of not finding a tensor that has been deleted earlier.
Fixes # (issue) https://github.com/OpenMined/OpenMined/pull/370
Tested with several examples in a jupyter notebook using debug logs to see when children are deleted. You can see that this works by trying:
```
a = FloatTensor(np.array([3,5,2]))
a.max()
a.max()
```
> Remove tensor from the graph of its creator(s) when deleted

- UnityProject/Assets/OpenMined.Tests/Editor/IntTensor/IntTensorTest.cs
- UnityProject/Assets/OpenMined/Syft/Tensor/IntTensor.Ops.cs
- UnityProject/Assets/OpenMined/Syft/Tensor/IntTensor.cs
- integration/test_int_tensor.py
- notebooks/tests/Test Tensor Function Implementations.ipynb
This pull request resolves issue #830 . This pull request is the Openmined Unity portion of the implementation. See comment below for the pull request of the PySyft portion.
* CPU: Macbook Pro (intel core i7)
* GPU: AMD Radeon R9 M370X
* PySyft Version: 0.1
* Unity Version: 2017.2.0f3
* OpenMined Unity App Version: Latest
> Implement the Acos function for IntTensor on the CPU #830

- UnityProject/Assets/OpenMined.Tests/Editor/IntTensor/IntTensorTest.cs
- UnityProject/Assets/OpenMined/Syft/Tensor/IntTensor.Ops.cs
- UnityProject/Assets/OpenMined/Syft/Tensor/IntTensor.cs
- notebooks/tests/Test Tensor Function Implementations.ipynb
This PR adds the unfold function for IntTensor OpenMined/PySyft#1266
Fixes OpenMined/PySyft#1266
* CPU: Intel Code i7 (4th Gen), Jupyter Notebook, Python 3.6
* GPU: n/a
* PySyft Version: 0.1.0
* Unity Version: 2017.2.0f3 Personal
* OpenMined Unity App Version: latest
> Implement Unfold function for IntTensor in Unity, fixes OpenMined/PySyft#1266

- UnityProject/Assets/OpenMined.Tests/Editor/IntTensor/IntTensorTest.cs
- UnityProject/Assets/OpenMined/Syft/Tensor/IntTensor.Ops.cs
Added initial support for addition and inline addition on the CPU for IntTensor.
Fix the IntTensor tests: Add and Add_ to actually test the IntTensor addition function (before it was testing the FloatTensor). Write additional IntTensor tests for AddScalar and AddScalar_. These unit tests are modified from the FloatTensorCPUTest and they pass.
https://github.com/OpenMined/PySyft/issues/766
https://github.com/OpenMined/PySyft/issues/767
These unit tests are modified from the FloatTensorCPUTest, using intTensorFactory instead.
* CPU: Mac OS High Sierra 10.13.3
* GPU: Radeon Pro 455 2 GB, Intel HD Graphics 530 1536 MB
* PySyft Version: 0.1
* Unity Version: 2017.3.1f1
* OpenMined Unity App Version: 2017.3.0f3
> implement the Add function and inline Add function for IntTensor on the CPU
